public with sharing class Constants {
    public static final String CASE_STATUS_SIGNED_AND_BILL = 'Production done and ready to bill';
    public static final String CASE_TEMP_SUBJECT = 'IO Contract For';
    public static final String DOCUMENT_NAME = '(IO Contract).pdf';
    public static final String CASE_ORIGIN_PDF = 'PDF';
    public static final String CASE_ORIGIN_RIGHT_SIGNATURE = 'Right Signature';
    public static final String CASE_ORIGIN_EMAIL = 'Email';
    public static final String ORDER_RECORD_TYPE = 'Order_Contract';
    public static final String USER_TYPE_SVP = 'SVP';
    public static final String USER_TYPE_MANAGER = 'MANAGER';
    public static final String USER_TYPE_MAIN = 'MAIN';
}